# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Research
    url: 'https://aovgun.weebly.com/research.html'
    weight: 20
  - name: Members
    url: 'https://aovgun.weebly.com/members.html'
    weight: 30
  - name: Publications
    url: 'https://aovgunpublications.netlify.app/'
    weight: 40
  - name: Press/Media
    url: 'https://aovgun.weebly.com/news.html'
    weight: 50   
  - name: Photos
    url: 'https://aovgun.weebly.com/photos.html'
    weight: 60  
  - name: Awards
    url: 'https://aovgun.weebly.com/awards.html'
    weight: 70   
  - name: Teaching
    url: 'https://aovgun.weebly.com/teaching.html'
    weight: 80   
  - name: Contact
    url: '#contact'
    weight: 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
